Repository BESTSELLER/harpocrates, pull requests merged in 2022-06, with the labels that each got.

#95 ES-2023 Upgrade CronJob apiVersion
  orb/CronJob.yml
Labels: minor, breaking-change

#97 ES-1983 Moved to Artifact registry and improved CircleCI config to `cci-common` orb
  .circleci/config.yml
  catalog-info.yaml
  examples/deployment.yaml
  orb/CronJob.yml
  orb/Deployment.yml
  orb/StatefulSet.yml
  orb/orb.yml
Labels: enhancement, patch

#99 fix for cronjob kustomize merge in kubectl 1.22
  orb/orb.yml
Labels: bug-fix

#100 wrong exec on kustomize, upgraded yq and fixed kustomize command
  orb/orb.yml
Labels: bug-fix

#101 fix for cronjobs.... again
  orb/orb.yml
Labels: bug-fix

#102 small mistakes fixed, like hardcoding the freaking deployment type. a…
  orb/orb.yml
Labels: bug-fix
