Repository BESTSELLER/harpocrates, pull requests merged in 2022-08, with the labels that each got.

#111 ES-2084 Validate secrets file from jsonschema
  cmd/root.go
  examples/secret.yaml
  go.mod
  go.sum
  test_data/README.md
  test_data/keys_with_prefix.json
  test_data/not_valid_test.json
  test_data/not_valid_test.yaml
  validate/schema.json
  validate/secretsFile.go
  validate/secretsFile_test.go
Labels: dependencies, major, feature, breaking-change

#114 added option to delete old secret file before fetching new ones
  orb/orb.yml
Labels: patch

#116 Validate on inject
  cmd/root.go
  config/config.go
  orb/orb.yml
Labels: minor
